modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="oedldoedlcore"
version="1.16.5-3.5.0"
displayName="Oedldoedl Series: Core"
displayURL="https://www.curseforge.com/minecraft/mc-mods/oedldoedl-core"
logoFile="oedldoedlcore.png"
authors="TheP2WKing"
description='''
[Oedldoedl Core Project]

Provides:
    - Tooltips
    - Information
    - Additional Recipes
    - Additional Tags
    - Vanilla Texture Fixes
    - Easier Creative Items Access
    - Survival Usable Wrenches
    - Additional JEI Descriptions
    - Additional JEI Catalysts
    - High Configurability
    - Common Modding Utilities
'''
[[dependencies.oedldoedlcore]]
    modId="forge"
    mandatory=true
    versionRange="[36.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.oedldoedlcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"